### ISSUE TITLE
define "particularly busy"

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#43]
> Line 92- define "particularly busy"- how did they determine when it was "busy" compared to normal? Do the authors have an estimate of how many busy days data was collected for? These busy days can pose the highest public health risk- particularly if they align with a contamination event.

**Comment by tomschenkjr** [comment]
@nicklucius - I know we don't have a definitive measure for this, but can you calculate how many weekend days where test data was collected (as a ratio of total days of collection)? This should provide a proxy for how often Parks collected data from being busy.

**Comment by nicklucius** [comment]
Here are the results of the calculation. This is for culture testing of E. coli only, because qPCR of enterococci has been done on weekends as a matter of course.

Beach Days of Collection | Weekend Beach Days of Collection | Ratio of Weekend to Total 
--------------------------- | -------------------------------------- | ----------------------------
 15464                              |                          486                          |                 0.03

**Comment by tomschenkjr** [comment]
Thanks, I'm going to edit this line and commit it directly to `dev`. I'll reassign to me.

**Comment by tomschenkjr** [comment]
@nicklucius - for the beach days calculated, how many years is that?

**Comment by nicklucius** [comment]
11 years of summers (2006 - 2016)
