### ISSUE TITLE
Did the authors attempt to make a model for the 5 "outlier" beaches

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/predicting-e-coli-concentrations#51]
> Line 245- Did the authors attempt to make a model for the 5 "outlier" beaches. Did these have similar characteristics that could be clustered together and a unique model made for them?

**Comment by tomschenkjr** [comment]
For this, let's push back on this comment. There are a few reasons why we don't want to pursue this line of research in this paper:

  * These beaches are distinct and difficult to predict. Need to identify literature which has also explored this and drawn supporting conclusions for these particular beaches in Chicago.
  * Other literature has supported that these features change the FIB characteristics. We should re-iterate this, especially since this paper is emphasizing inter-beach correlations.
  * We should find any supporting literature of the city messing with breakwaters to align them to FIB characteristics of other beaches. This supports the notion that a predictive model isn't worth pursuing for these beaches.

**Comment by nicklucius** [comment]
Here is the original source, from Whitman and Nevers, which led to the breakwater analysis and subsequent removal of certain beaches from the model: [Escherichia coli Sampling Reliability at a Frequently Closed Chicago Beach:  Monitoring and Management Implications](https://pubs.acs.org/doi/full/10.1021/es034978i), which cites [Foreshore Sand as a Source of Escherichia coli in Nearshore Water of a Lake Michigan Beach](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC194947/) by the same authors. 

Both papers are case studies of 63rd Avenue Beach in Chicago, and discuss the mechanisms which presumably result in higher E. coli levels due to the breakwater.

Regarding the city messing with breakwaters, I've pinged the Park District to check in on that.

**Comment by tomschenkjr** [comment]
@nicklucius - let's include a brief explanation for this in the [submission letter to the editor](https://github.com/Chicago/predicting-e-coli-concentrations/wiki/Letter-to-Editor-for-Revision). Use these references to create a paragraph on this topic.

**Comment by nicklucius** [comment]
@tomschenkjr - I added a paragraph to the [letter](https://github.com/Chicago/predicting-e-coli-concentrations/wiki/Letter-to-Editor-for-Revision). Please review.

**Comment by tomschenkjr** [comment]
Looks good
